# Generated by Django 3.2.9 on 2023-06-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('ResultId', models.AutoField(primary_key=True, serialize=False)),
                ('ResultTime', models.CharField(max_length=50)),
                ('Result', models.CharField(max_length=50)),
            ],
        ),
    ]
